# Cloudflare Pages Build Configuration
[build]
  # Build command
  command = "cd mashinc-realty && npm run build"
  
  # Output directory (relative to repo root)
  publish = "mashinc-realty"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# Development preview settings
[context.production]
  command = "cd mashinc-realty && npm run build"
  publish = "mashinc-realty"

[context.deploy-preview]
  command = "cd mashinc-realty && npm run build"
  publish = "mashinc-realty"

[context.branch-deploy]
  command = "cd mashinc-realty && npm run build"
  publish = "mashinc-realty"
